// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Random = require("bs-platform/lib/js/random.js");

function unique(param) {
  return Random.$$int(Date.now() | 0);
}

var Identifier = /* module */[/* unique */unique];

exports.Identifier = Identifier;
/* No side effect */
